# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: '4.0'}
          #- {os: ubuntu-20.04, r: '4.0', rspm: "https://demo.rstudiopm.com/all/__linux__/focal/latest"}
    runs-on: ${{ matrix.config.os }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RSPM: ${{ matrix.config.rspm }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install pacman
        run: Rscript -e 'install.packages("pacman")'
      - name: Run script
        run: Rscript cdc_violence.R
      - name: Commit files
        run: |
          git add chart.png
          git commit -m 'Re-build chart' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
